"""Initial migration.

Revision ID: 0915b4b1f5fe
Revises: 
Create Date: 2021-03-18 15:31:10.618200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0915b4b1f5fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1280), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('transmission', sa.String(length=128), nullable=True),
    sa.Column('img', sa.String(length=128), nullable=True),
    sa.Column('img1', sa.String(length=128), nullable=True),
    sa.Column('img2', sa.String(length=128), nullable=True),
    sa.Column('img3', sa.String(length=128), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('date_and_time_rent_start', sa.DateTime(), nullable=True),
    sa.Column('date_and_time_rent_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent')
    op.drop_table('car')
    # ### end Alembic commands ###
