"""BLOB

Revision ID: 739b7532c067
Revises: 0915b4b1f5fe
Create Date: 2022-10-26 20:18:37.060027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739b7532c067'
down_revision = '0915b4b1f5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('люди')
    op.alter_column('car', 'description',
               existing_type=sa.TEXT(length=1280),
               nullable=False)
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'Campaign_ID')
    op.drop_column('rent', 'Campaign_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rent', sa.Column('Campaign_ID', sa.NUMERIC(precision=50), nullable=True))
    op.add_column('car', sa.Column('Campaign_ID', sa.NUMERIC(precision=50), nullable=True))
    op.create_foreign_key(None, 'car', 'rent', ['Campaign_ID'], ['Campaign_ID'])
    op.alter_column('car', 'description',
               existing_type=sa.TEXT(length=1280),
               nullable=True)
    op.create_table('люди',
    sa.Column('Фамилия', sa.CHAR(), nullable=True),
    sa.Column('Имя', sa.CHAR(), nullable=True),
    sa.Column('Возраст', sa.INTEGER(), nullable=True),
    sa.Column('Пол', sa.CHAR(), nullable=True),
    sa.Column('Цвет_глаз', sa.CHAR(), nullable=True),
    sa.Column('Цвет_волос', sa.CHAR(), nullable=True),
    sa.Column('Размер_ноги', sa.INTEGER(), nullable=True),
    sa.Column('Рост', sa.INTEGER(), nullable=True),
    sa.Column('Вес', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
